import { Inter } from "next/font/google";
import "./globals.css";
import Animation from "@/components/animation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Animation>{children}</Animation>
        </body>
    </html>
  );
}
